name: Deploy ios to production

on:
  push:
    branches: ["master"]

jobs:
  fingerprint: # Takes a hash of the native characteristics of the project using Expo Fingerprint
    name: Fingerprint
    type: fingerprint
  get_ios_build: # Checks if a build already exists for the fingerprint
    name: Check for existing ios build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      profile: production
  build_ios: # If a build does not exist, it will build the project
    name: Build iOS
    needs: [get_ios_build]
    if: ${{ !needs.get_ios_build.outputs.build_id }}
    type: build
    params:
      platform: ios
      profile: production
  submit_ios: # Submit it to the app stores after build
    name: Submit to Apple App Store
    needs: [build_ios]
    type: submit
    params:
      platform: ios
      build_id: ${{ needs.build_ios.outputs.build_id }}
  publish_ios_update: # If a build exists, it will send an over-the-air update
    name: Publish iOS update
    needs: [get_ios_build]
    if: ${{ needs.get_ios_build.outputs.build_id }}
    type: update
    params:
      branch: production
      platform: ios
